/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BasicLoanInformation { 
    loanId?: string;
    amount?: number;
    totalAmount?: number;
    interest?: number;
    dateTime?: string;
    numberDate?: number;
    total?: number;
}

