/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BasicBorrowerClientWithTags } from './basicBorrowerClientWithTags';


export interface BasicBorrowerClientWithTagsPaginationResponse { 
    pageSize?: number;
    currentPage?: number;
    orderBy?: string[] | null;
    totalItems?: number;
    result?: BasicBorrowerClientWithTags[] | null;
}

