/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleLoanDtoAndPayments } from './simpleLoanDtoAndPayments';


export interface BasicBorrowerClientWithTagsAndLoans { 
    id?: string;
    name?: string | null;
    dni?: string | null;
    phoneNumber?: string | null;
    title?: string | null;
    tags?: string[] | null;
    loans?: SimpleLoanDtoAndPayments[] | null;
}

