/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BasicBorrowerClientWithTags { 
    id?: string;
    name?: string | null;
    tags?: Array<string> | null;
    paymentToday?: number;
}

