/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BasicLoanDto } from './basicLoanDto';


export interface BasicLoanDtoPaginationResponse { 
    pageSize?: number;
    currentPage?: number;
    orderBy?: Array<string> | null;
    totalItems?: number;
    result?: Array<BasicLoanDto> | null;
}

