/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BorrowerClientDto { 
    id?: string;
    avatar?: string | null;
    background?: string | null;
    name?: string | null;
    dni?: string | null;
    dniPath?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    title?: string | null;
    company?: string | null;
    birthday?: string | null;
    address?: string | null;
    notes?: string | null;
    status?: string | null;
    stringTags?: string | null;
}

