/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BorrowerClientDto } from './borrowerClientDto';


export interface BorrowerClientDtoNewBorrowerClientDto { 
    borrowerClientDto?: BorrowerClientDto;
    tagIdList?: Array<string> | null;
}

