/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentDto } from './paymentDto';


export interface CompleteLoanDto { 
    id?: string;
    amount?: number;
    interest?: number;
    dateTime?: string;
    numberDate?: number;
    borrowerClientId?: string;
    total?: number;
    totalDebt?: number;
    name?: string | null;
    tags?: string[] | null;
    payments?: PaymentDto[] | null;
}

