/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CountryDto { 
    id?: string | null;
    iso?: string | null;
    name?: string | null;
    code?: string | null;
    flagImagePos?: string | null;
}

