/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanType } from './loanType';


export interface CreateLoanDto { 
    amount?: number;
    interest?: number;
    numberDate?: number;
    loanType?: LoanType;
    suggestedDays?: string[] | null;
    borrowerClientId?: string;
}
export namespace CreateLoanDto {
}


