/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BorrowerClient } from './borrowerClient';
import { Payment } from './payment';
import { LoanType } from './loanType';
import { PointDto } from './pointDto';


export interface Loan { 
    id?: string;
    changeBy?: string;
    changeDate?: string;
    isDeleted?: boolean;
    amount?: number;
    interest?: number;
    dateTime?: string;
    numberDate?: number;
    loanType?: LoanType;
    suggestedDays?: Array<string> | null;
    borrowerClientId?: string;
    borrowerClient?: BorrowerClient;
    payments?: Array<Payment> | null;
    currentLocation?: PointDto;
}
export namespace Loan {
}


