/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanAndDate { 
    loanId?: string;
    name?: string | null;
    title?: string | null;
    amount?: number;
    interest?: number;
    tag?: string | null;
    dateTime?: string;
}

