/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoansByMonthDto } from './loansByMonthDto';


export interface LoansByMonthDtoMetadata { 
    name?: string | null;
    data?: Array<LoansByMonthDto> | null;
}

