/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanType } from './loanType';
import { SimplePayments } from './simplePayments';


export interface LoanDtoAndPayments { 
    id?: string;
    amount?: number;
    interest?: number;
    dateTime?: string;
    numberDate?: number;
    loanType?: LoanType;
    totalPayment?: number;
    totalAmount?: number;
    payments?: Array<SimplePayments> | null;
    status?: string | null;
    progressPercentage?: number;
}
export namespace LoanDtoAndPayments {
}


