/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Loan } from './loan';
import { PointDto } from './pointDto';


export interface Payment { 
    id?: string;
    changeBy?: string;
    changeDate?: string;
    isDeleted?: boolean;
    dateTime?: string;
    amount?: number;
    location?: PointDto;
    isYape?: boolean;
    isRefinance?: boolean;
    loanId?: string;
    loan?: Loan;
}

