/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentDto } from './paymentDto';


export interface PaymentDtoPaginationResponse { 
    pageSize?: number;
    currentPage?: number;
    orderBy?: string[] | null;
    totalItems?: number;
    result?: PaymentDto[] | null;
}

