/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportPaymentsDto } from './reportPaymentsDto';


export interface ReportPaymentByDayDto { 
    dateTime?: string;
    totalPayment?: number;
    detailsDto?: ReportPaymentsDto[] | null;
}

