/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportPaymentsDto { 
    id?: string;
    changeBy?: string;
    name?: string | null;
    title?: string | null;
    tagId?: string;
    loanDate?: string;
    amount?: number;
    payment?: number;
    isYape?: boolean;
}

