/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BasicLoanInformation } from './basicLoanInformation';
import { TagDto } from './tagDto';
import { BorrowerClientDto } from './borrowerClientDto';


export interface ResponseBorrowerClientDto { 
    tagDto?: Array<TagDto> | null;
    borrowerClientDto?: BorrowerClientDto;
    basicLoanInformation?: Array<BasicLoanInformation> | null;
}

