/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimplePayments } from './simplePayments';


export interface SimpleLoanDtoAndPayments { 
    id?: string;
    amount?: number;
    interest?: number;
    dateTime?: string;
    numberDate?: number;
    borrowerClientId?: string;
    totalAmount?: number;
    totalPayment?: number;
    payments?: SimplePayments[] | null;
}

