/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagBorrowerClient } from './tagBorrowerClient';


export interface Tag { 
    id?: string;
    changeBy?: string;
    changeDate?: string;
    isDeleted?: boolean;
    title?: string | null;
    person?: Array<TagBorrowerClient> | null;
}

