/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BorrowerClient } from './borrowerClient';
import { Tag } from './tag';


export interface TagBorrowerClient { 
    id?: string;
    changeBy?: string;
    changeDate?: string;
    isDeleted?: boolean;
    tagId?: string;
    borrowerClientId?: string;
    tag?: Tag;
    borrowerClient?: BorrowerClient;
}

