/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TagDto } from './tagDto';


export interface TagDtoPaginationResponse { 
    pageSize?: number;
    currentPage?: number;
    orderBy?: string[] | null;
    totalItems?: number;
    result?: TagDto[] | null;
}

