/**
 * MyAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateBorrowerClientDto } from './updateBorrowerClientDto';


export interface UpdateBorrowerClientDtoNewBorrowerClientDto { 
    borrowerClientDto?: UpdateBorrowerClientDto;
    tagIdList?: string[] | null;
}

